//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EXON.MONITOR.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EXON.MONITOR.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap add16 {
            get {
                object obj = ResourceManager.GetObject("add16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap checklist {
            get {
                object obj = ResourceManager.GetObject("checklist", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap customer_service {
            get {
                object obj = ResourceManager.GetObject("customer-service", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MTA_QUIZ_1.
        /// </summary>
        internal static string DATABASE_NAME {
            get {
                return ResourceManager.GetString("DATABASE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 123.
        /// </summary>
        internal static string DATABASE_PASS {
            get {
                return ResourceManager.GetString("DATABASE_PASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1433.
        /// </summary>
        internal static string DATABASE_PORT {
            get {
                return ResourceManager.GetString("DATABASE_PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sa.
        /// </summary>
        internal static string DATABASE_USER {
            get {
                return ResourceManager.GetString("DATABASE_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete16 {
            get {
                object obj = ResourceManager.GetObject("delete16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Excel_icon {
            get {
                object obj = ResourceManager.GetObject("Excel-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap filter {
            get {
                object obj = ResourceManager.GetObject("filter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap info {
            get {
                object obj = ResourceManager.GetObject("info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keybooo {
            get {
                object obj = ResourceManager.GetObject("keybooo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap loading {
            get {
                object obj = ResourceManager.GetObject("loading", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap loading1 {
            get {
                object obj = ResourceManager.GetObject("loading1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap loading2 {
            get {
                object obj = ResourceManager.GetObject("loading2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LogoHVnew3 {
            get {
                object obj = ResourceManager.GetObject("LogoHVnew3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap monitor {
            get {
                object obj = ResourceManager.GetObject("monitor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap monitor_dubi {
            get {
                object obj = ResourceManager.GetObject("monitor_dubi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap monitor_hong {
            get {
                object obj = ResourceManager.GetObject("monitor_hong", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap monitor_khongcothisinh {
            get {
                object obj = ResourceManager.GetObject("monitor_khongcothisinh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi kết nối.
        /// </summary>
        internal static string MSG_ERR_001 {
            get {
                return ResourceManager.GetString("MSG_ERR_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian bắt đầu: .
        /// </summary>
        internal static string MSG_GUI_001 {
            get {
                return ResourceManager.GetString("MSG_GUI_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian kết thúc: .
        /// </summary>
        internal static string MSG_GUI_002 {
            get {
                return ResourceManager.GetString("MSG_GUI_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang tổ chức thi.
        /// </summary>
        internal static string MSG_GUI_003 {
            get {
                return ResourceManager.GetString("MSG_GUI_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ca thi chưa mở.
        /// </summary>
        internal static string MSG_GUI_004 {
            get {
                return ResourceManager.GetString("MSG_GUI_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ca thi kết thúc.
        /// </summary>
        internal static string MSG_GUI_005 {
            get {
                return ResourceManager.GetString("MSG_GUI_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ca thi: Đã giải mã đề.
        /// </summary>
        internal static string MSG_GUI_006 {
            get {
                return ResourceManager.GetString("MSG_GUI_006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ca thi: Đã phát đề.
        /// </summary>
        internal static string MSG_GUI_007 {
            get {
                return ResourceManager.GetString("MSG_GUI_007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ca thi: Đã bắt đầu làm.
        /// </summary>
        internal static string MSG_GUI_008 {
            get {
                return ResourceManager.GetString("MSG_GUI_008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ca thi: Chưa giải mã đề.
        /// </summary>
        internal static string MSG_GUI_009 {
            get {
                return ResourceManager.GetString("MSG_GUI_009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiếp tục phòng thi.
        /// </summary>
        internal static string MSG_GUI_010 {
            get {
                return ResourceManager.GetString("MSG_GUI_010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạm dừng phòng thi.
        /// </summary>
        internal static string MSG_GUI_011 {
            get {
                return ResourceManager.GetString("MSG_GUI_011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phòng thi đang tạm dừng.
        /// </summary>
        internal static string MSG_GUI_012 {
            get {
                return ResourceManager.GetString("MSG_GUI_012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR.
        /// </summary>
        internal static string MSG_LOG_ERROR {
            get {
                return ResourceManager.GetString("MSG_LOG_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FATAL.
        /// </summary>
        internal static string MSG_LOG_FATAL {
            get {
                return ResourceManager.GetString("MSG_LOG_FATAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INFO.
        /// </summary>
        internal static string MSG_LOG_INFO {
            get {
                return ResourceManager.GetString("MSG_LOG_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARN.
        /// </summary>
        internal static string MSG_LOG_WARN {
            get {
                return ResourceManager.GetString("MSG_LOG_WARN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa cho phép vào phòng thi, bạn chỉ có thể vào phòng thi trước khi thi 30 phút hoặc sau khi kết thúc ca thi.
        /// </summary>
        internal static string MSG_WAR_001 {
            get {
                return ResourceManager.GetString("MSG_WAR_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phòng thi đã được bắt đầu!.
        /// </summary>
        internal static string MSG_WAR_002 {
            get {
                return ResourceManager.GetString("MSG_WAR_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phòng thi đã phát đề cho thí sinh!.
        /// </summary>
        internal static string MSG_WAR_003 {
            get {
                return ResourceManager.GetString("MSG_WAR_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phòng thi đã kết thúc!.
        /// </summary>
        internal static string MSG_WAR_004 {
            get {
                return ResourceManager.GetString("MSG_WAR_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thí sinh chưa tải xong đề thi! Vui lòng kiểm tra lại trạng thái của thí sinh!.
        /// </summary>
        internal static string MSG_WAR_005 {
            get {
                return ResourceManager.GetString("MSG_WAR_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiểm tra lại thí sinh! Có thí sinh chưa đổi trạng thái hoàn thành thi!.
        /// </summary>
        internal static string MSG_WAR_006 {
            get {
                return ResourceManager.GetString("MSG_WAR_006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể kết nối server.
        /// </summary>
        internal static string NotConnectServerMessage {
            get {
                return ResourceManager.GetString("NotConnectServerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo.
        /// </summary>
        internal static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sai mật khẩu hoặc tài khoản.
        /// </summary>
        internal static string NotLoginMessage {
            get {
                return ResourceManager.GetString("NotLoginMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap placeholder {
            get {
                object obj = ResourceManager.GetObject("placeholder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap question {
            get {
                object obj = ResourceManager.GetObject("question", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap refresh162 {
            get {
                object obj = ResourceManager.GetObject("refresh162", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap report {
            get {
                object obj = ResourceManager.GetObject("report", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap search16 {
            get {
                object obj = ResourceManager.GetObject("search16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap search24 {
            get {
                object obj = ResourceManager.GetObject("search24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHANDUY.
        /// </summary>
        internal static string SERVER_NAME {
            get {
                return ResourceManager.GetString("SERVER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHANDUY\\SQLEXPRESS,1433.
        /// </summary>
        internal static string SERVER_NAME_THI {
            get {
                return ResourceManager.GetString("SERVER_NAME_THI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAYCHUTHI\\SQLEXPRESS,1433.
        /// </summary>
        internal static string SERVER_NAME_TRUNGTAM {
            get {
                return ResourceManager.GetString("SERVER_NAME_TRUNGTAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap stats {
            get {
                object obj = ResourceManager.GetObject("stats", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap stick_man {
            get {
                object obj = ResourceManager.GetObject("stick-man", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap student {
            get {
                object obj = ResourceManager.GetObject("student", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap study {
            get {
                object obj = ResourceManager.GetObject("study", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Supervisor {
            get {
                object obj = ResourceManager.GetObject("Supervisor", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap television {
            get {
                object obj = ResourceManager.GetObject("television", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CẢNH CÁO.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
